apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  labels:
    app: springOauthRepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springOauthRepo
  template:
    metadata:
      labels:
        app: springOauthRepo
    spec:
      containers:
        - name: springOauthRepo
          image: sriharipriya/springOauthRepo:${{ github.run_number }}

          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservices-poc-loadbalancer-service
  labels:
    app: springOAuthRepo
spec:
  type: LoadBalancer
  selector:
    app: springOAuthRepo
  ports:
    - port: 8080
      targetPort: 8080
